# App
name = "ImThemes"
comment = "ImThemes is a Dear ImGui theme designer and browser written in Nim"
version = "0.2.6"
website = "https://github.com/Patitotective/ImThemes"
authors = ["Patitotective <https://github.com/Patitotective>"]
categories = ["Utility"]

# AppImage
ghRepo = "Patitotective/ImThemes"

stylePath = "assets/style.toml"
iconPath = "assets/icon.png"
svgIconPath = "assets/icon.svg"
iconFontPath = "assets/forkawesome-webfont.ttf"
fontPath = "assets/Karla-Regular.ttf"
strongFontPath = "assets/Karla-Bold.ttf"
fontSize = 18.0

# Window
minSize = [700, 500] # Width, height

# Settings for the preferences window
[[settings]]
name = "proxy"
display = "Proxy"
type = "input"
default = ""
max = 100
help = "Remember to include the protocol (e.i.: http)"
flags = "None" # See https://nimgl.dev/docs/imgui.html#ImGuiInputTextFlags
[[settings]]
name = "proxyUser"
type = "input"
default = ""
hint = "optional"
display = "Proxy Username"
max = 100
flags = "None" # See https://nimgl.dev/docs/imgui.html#ImGuiInputTextFlags
[[settings]]
name = "proxyPassword"
type = "input"
hint = "optional"
default = ""
display = "Proxy Password"
max = 100
flags = "None" # See https://nimgl.dev/docs/imgui.html#ImGuiInputTextFlags
